### ISSUE TITLE
bug when running `python experiments/mtl_gravity_tasks/half_cheetah_stl.py`

### ISSUE THREAD

**Issue by optimass** [Lifelong-ML/LPG-FTW#2]
Hello,

Great work!

I have the following bug when running `python experiments/mtl_gravity_tasks/half_cheetah_stl.py`

```
......................................................................................
ITERATION : 49 
####### Gathering Samples #######
======= Samples Gathered  ======= | >>>> Time taken = 1.489592 
[ Thu Aug 26 14:06:30 2021 ]   49 986.84  0.00 969.95 
----------------  -------------
VF_error_after       0.0124407
VF_error_before      0.0141749
alpha               11.4923
delta                1
kl_dist              0.50761
running_score      732.982
stoc_pol_max      1070.37
stoc_pol_mean      986.836
stoc_pol_min       880.297
stoc_pol_std        61.4324
surr_improvement     0.0765501
time_VF              0.801421
time_npg             0.175905
time_sampling        1.48979
time_vpg             0.00862265
----------------  -------------
####### Gathering Samples #######
======= Samples Gathered  ======= | >>>> Time taken = 1.642998 
Traceback (most recent call last):
  File "experiments/mtl_gravity_tasks/half_cheetah_stl.py", line 82, in <module>
    num_cpu=num_cpu)
  File "/home/ubuntu/dev/LPG-FTW/mjrl/algos/npg_cg.py", line 197, in add_approximate_cost
    self.grad_and_hess(observations, actions, advantages)
  File "/home/ubuntu/dev/LPG-FTW/mjrl/algos/npg_cg.py", line 119, in grad_and_hess
    vpg_grad[2].view(-1,1),
IndexError: tuple index out of range
```

Seems to crash before going to second task.

**Comment by jorge-a-mendez** [comment]
Hi, thanks for your interest in our work! I just started looking into this, and it seems to be an issue only for STL training when running `add_approximate_cost`. I will try to fix this soon.

In the meantime, depending on your use-case, you might be able to simply comment out lines 81-84 and 94-99 in `half_cheetah_stl.py`. Those are only used to store the Hessian and gradient information to be used later by PG-ELLA, so if you're not interested in running PG-ELLA, you won't need them.
